import { build } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";

const result = await build({
  entryPoints: [
    fileURLToPath(new URL("../src/api/checkout-browser.ts", import.meta.url)),
  ],
  bundle: true,
  platform: "browser",
  format: "iife",
  target: "es2022",
  minify: true,
  legalComments: "inline",
  write: false,
});
const script = result.outputFiles[0]!.text;
const markup = await readFile(
  new URL("../src/api/checkout.ts", import.meta.url),
  "utf8",
);
const assetVersion = createHash("sha256")
  .update(script)
  .update(markup)
  .digest("hex")
  .slice(0, 16);
await writeFile(
  new URL("../src/api/checkout.generated.ts", import.meta.url),
  "// Generated by npm run build:checkout; do not edit.\nexport const CHECKOUT_JS = " +
    JSON.stringify(script) +
    ";\nexport const CHECKOUT_ASSET_VERSION = " +
    JSON.stringify(assetVersion) +
    ";\n",
);
console.log(
  `Built same-origin PayIn checkout (${Buffer.byteLength(script)} bytes).`,
);
